name: CI

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  scan_ruby:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true

      - name: Scan for common Rails security vulnerabilities using static analysis
        run: bundle exec brakeman --no-pager

  scan_js:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true

      - name: Scan for security vulnerabilities in JavaScript dependencies
        # Use the Rails-provided script instead of a gem executable
        run: ruby bin/importmap audit

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true

      - name: Lint code for consistent style
        run: bundle exec rubocop -f github

  test_rspec:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: howdy
          POSTGRES_DB: project3_group4_test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      PGHOST: postgres
      PGUSER: postgres
      PGPASSWORD: howdy
      PGDATABASE: project3_group4_test
      RAILS_ENV: test
      WITH_COVERAGE: true
      DISABLE_SPRING: 1

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true

      - name: Install bundler and postgresql dependencies
        run: |
          sudo apt install -yqq libpq-dev
          gem install bundler

      - name: Install Gems
        run: bundle install

      - name: Setup database
        run: bundle exec rails db:prepare

      - name: Build and test with rspec
        run: bundle exec rspec spec

      - name: Create Coverage Artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: rspec-code-coverage
          path: coverage/

  test_cucumber:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: howdy
          POSTGRES_DB: project3_group4_test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      PGHOST: postgres
      PGUSER: postgres
      PGPASSWORD: howdy
      PGDATABASE: project3_group4_test
      RAILS_ENV: test
      WITH_COVERAGE: true
      DISABLE_SPRING: 1

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true

      - name: Install bundler and postgresql dependencies
        run: |
          sudo apt install -yqq libpq-dev
          gem install bundler

      - name: Install Gems
        run: bundle install

      - name: Setup database
        run: bundle exec rails db:prepare

      - name: Run cucumber tests
        run: bundle exec cucumber

      - name: Create Coverage Artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cucumber-code-coverage
          path: coverage/